config-version: 5 # Config version, you should never manually change this.

###############
# Core Config #
###############
# Core config for backend processes or misc options.
# If you are looking to edit graves the main grave config file is grave.yml.
settings:
  ###########
  # Storage #
  ###########
  # Data storage system.
  storage:
    type: SQLITE # Available options: SQLITE, MYSQL, MARIADB, POSTGRESQL, H2. More storage types will be added in the future.

    sqlite:
      # Unless you know what you're doing, leave the options under sqlite default.
      journal-mode: "WAL" # Journal mode for SQLite. Options include DELETE, TRUNCATE, PERSIST, MEMORY, WAL, OFF. Refer to https://www.sqlite.org/pragma.html#pragma_journal_mode for more details.
      synchronous: "OFF" # Synchronous mode for SQLite. Options include 0 (OFF), 1 (NORMAL), 2 (FULL), 3 (EXTRA). Refer to https://www.sqlite.org/pragma.html#pragma_synchronous for more details.

    mysql:
      # Unless you know what you're doing, leave the options under mysql default.
      host: "localhost" # Host of the MySQL database.
      port: 3306 # Port for the MySQL database (do not change unless you use a different port).
      username: "username" # Database username. Ensure the user has access to the database.
      password: "password" # Database password. Case-sensitive.
      database: "graves" # Database to use.
      maxConnections: 10 # Maximum number of connections allowed to the database. Do not change unless you know what you are doing.
      maxLifetime: 1800000 # Maximum lifetime of a connection in milliseconds. DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      connectionTimeout: 30000 # Connection timeout in milliseconds. DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING. Only increase if your connection keeps timing out.
      useSSL: false # Should we use SSL? Unless you know what you are doing, leave this at false.
      allowPublicKeyRetrieval: false # Should we allow public key retrieval? DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      verifyServerCertificate: false # Should we verify the server certificate? DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.

    postgresql:
      # Unless you know what you're doing, leave the options under postgresql default.
      host: "localhost" # Host of the PostgreSQL database.
      port: 5432 # Port for the PostgreSQL database (do not change unless you use a different port).
      username: "username" # Database username. Ensure the user has access to the database.
      password: "password" # Database password. Case-sensitive.
      database: "graves" # Database to use.
      maxConnections: 10 # Maximum number of connections allowed to the database. Do not change unless you know what you are doing.
      maxLifetime: 1800000 # Maximum lifetime of a connection in milliseconds. DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      connectionTimeout: 30000 # Connection timeout in milliseconds. DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING. Only increase if your connection keeps timing out.
      ssl: false # Should we use SSL? Unless you know what you are doing, leave this at false.
      sslfactory: "org.postgresql.ssl.NonValidatingFactory" # SSL factory class. Default: org.postgresql.ssl.NonValidatingFactory. Refer to PostgreSQL SSL documentation for more details.
      sslmode: "disable" # SSL mode. Options include disable, allow, prefer, require, verify-ca, verify-full. Refer to PostgreSQL SSL documentation for more details.
      sslrootcert: "/path/to/server.crt" # Path to the server root certificate.
      sslcert: "/path/to/client.crt" # Path to the SSL certificate.
      sslkey: "/path/to/client.key" # Path to the SSL key.

    h2:
      # Unless you know what you're doing, leave the options under h2 default.
      username: "sa" # Username for the H2 database.
      password: "" # Password for the H2 database. The default is an empty string.
      maxConnections: 50 # Maximum number of connections allowed to the database. Do not change unless you know what you are doing.
      maxLifetime: 1800000 # Maximum lifetime of a connection in milliseconds. DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      connectionTimeout: 30000 # Connection timeout in milliseconds. DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING. Only increase if your connection keeps timing out.



  #########
  # Cache #
  #########
  # Data storage system.
  cache:
    type: NORMAL # Cache type. Implementation Unused

  #########
  # Debug #
  #########
  # Debug information, debug level 2 can be useful in finding out why a Grave does not spawn on your server.
  debug:
    admin: # UUID or name of admins to send debug information to. https://mcuuid.net/
      - "c59ac6d2-4851-4183-a9f7-15d1a293eed6" # Ranull
      - "069a79f4-44e9-4726-a5be-fca90e38aaf5" # Notch
    level: 0 # 0 = Nothing, 1 = Information, 2 = Failures

  #########
  # Dump #
  #########
  # Dump server information to help debug the plugin.
  # Methods: MCLOGS, FILE
  dump:
    method: MCLOGS # MCLOGS, FILE

  ##########
  # Update #
  ##########
  update:
    check: true # Should Graves try and check for an update.

  ###########
  # Metrics #
  ###########
  metrics:
    enabled: true # Should we report metrics to bstats? Available here: https://bstats.org/plugin/bukkit/Graves/12849

  #################
  # Compatibility #
  #################
  compatibility:
    warning: true # Warn when a plugin to have known incompatibilities is detected.

  ###############
  # Integration #
  ###############
  # Enable/Disable integrations into other plugins, if you are having errors relating to another plugin
  # try disabling them here.
  integration:
    multipaper: # https://multipaper.io/
      enabled: true # Should MultiPaper integration be enabled.
    multicache: # https://github.com/PestoNotPasta/MultiCache/
      enabled: true # Should MultiCache integration be enabled.
    vault: # https://www.spigotmc.org/resources/vault.34315/
      enabled: true # Should Vault integration be enabled.
    protocollib: # https://www.spigotmc.org/resources/protocollib.1997/
      enabled: true # Should ProtocolLib integration be enabled.
    worldedit: # https://dev.bukkit.org/projects/worldedit/
      enabled: true # Should WorldEdit integration be enabled.
      write: true # Should Graves write its schematics into its own folder.
    worldguard: # https://dev.bukkit.org/projects/worldguard/
      enabled: true # Should WorldGuard integration be enabled.
    towny: # https://www.spigotmc.org/resources/towny-advanced.72694/
      enabled: true # Should Towny integration be enabled.
    griefdefender: # https://www.spigotmc.org/resources/griefdefender.68900/
      enabled: true # Should GriefDefender integration be enabled.
    furniturelib: # https://www.spigotmc.org/resources/furniturelibary.9368/
      enabled: true # Should FurnitureLib integration be enabled.
    furnitureengine: # https://www.spigotmc.org/resources/furnitureengine.97134/
      enabled: true # Should FurnitureEngine integration be enabled.
    protectionlib: # https://www.spigotmc.org/resources/protectionlib.9368/
      enabled: true # Should ProtectionLib integration be enabled.
    itemsadder: # https://www.spigotmc.org/resources/itemsadder.73355/
      enabled: true # Should ItemsAdder integration be enabled.
      write: true # Should Graves write its data into the ItemsAdder data folder.
    oraxen: # https://www.spigotmc.org/resources/oraxen.72448/
      enabled: true # Should Oraxen integration be enabled.
      write: true # Should Graves write its pack into the Oraxen pack folder.
    placeholderapi: # https://www.spigotmc.org/resources/placeholderapi.6245/
      enabled: true # Should PlaceholderAPI integration be enabled.
    skript: # https://github.com/SkriptLang/Skript/
      enabled: true # Should Skript integration be enabled.
    chestsort: # https://www.spigotmc.org/resources/chestsort.59773/
      enabled: true # Should ChestSort integration be enabled.
    minimessage: # https://docs.adventure.kyori.net/minimessage/index.html
      enabled: true # Should MiniMessage integration be enabled.
    minedown: # https://github.com/Phoenix616/MineDownPlugin/
      enabled: true # Should MineDown integration be enabled.
    playernpc: # https://www.spigotmc.org/resources/playernpc.93625/
      enabled: true # Should PlayerNPC integration be enabled.
    citizensnpc: # https://www.spigotmc.org/resources/citizens.13811/
      enabled: true # Should Citizens integration be enabled.
    itembridge: # https://www.spigotmc.org/resources/itembridge.77080/
      enabled: true # Should ItemBridge integration be enabled.
